example.com:
  SOA:
    serial: 0101010101
    refresh: 3600
    retry: 300
    expire: 3600000
    minimum: 3600
  records:
    NS:
      - ns1
      - ns2
    A:
      ns1:
        default: '1.1.1.1'
      ns2:
        default: '2.2.2.2'
      a:
        default: '127.1.1.1'
        map: primary
        ttl: 30
      any:
        default: '1.0.0.1'
        map: primary
        ttl: 30

maps:
  primary:
    us-east: '127.0.1.1'
    us-west: '127.1.0.1'
